### ISSUE TITLE
Clean code

### ISSUE THREAD

**Issue by manuelgitgomes** [AutoMecUA/AutoMec-AD#143]
Due to last-minute changes and bad coding practices, code cleansing needs to happen.
- [x] Clean CNN code, implement naming for datasets and models, renew yamls - @brnaguiar;
- [x] Clean signal recognition code - @Almeida-a @manuelgitgomes;
- [x] Clean ROS launch files - @manuelgitgomes;

**Comment by brnaguiar** [comment]
datasets:
    real/:
        [estadio/fnr/...]-[dia]-[mes]-[hora]/
        exemplo: estadio-02-01-12h30/
    gazebo/:
        gazebo-[dia]-[mes]-[hora]
        exemplo: gazebo-02-01-12h30/

modelos (.h5):
    [model]-[dia]-[mes]-[hora]-[loss].h5
    exemplo: rota-02-01-12h50-011.h5

**Comment by manuelgitgomes** [comment]
As seen in other repos such as Major Alvega's and AtlasCar2's, a refactoring of our packages is needed to reduce the number of packages and the complexity.
I suggest doing as follows:

- prometheus_bringup: Every bringup file should be here, from writing, to driving, etc... This would be a junction of current physical_bringup, robot_driving and parts of simulation_bringup;
- prometheus_description: The same as the current traxxas_description;
- prometheus_driving: Everything used for the AD should be placed here (CNN, RNN, IPM), etc;
- prometheus_gazebo: Everything gazebo related should be here (arena, signal panel control, etc...). This would allow the various scripts and launch files of other packages to be the same for physical and simulation;
- prometheus_signal_recognition: The same as the current signal_recognition;

In the future, we can add other packages such as prometheus_vertical_signals, prometheus_parking, etc....


Examples shown here:
![MicrosoftTeams-image (12)](https://user-images.githubusercontent.com/58152228/168496357-9f6eb472-37e7-40d6-a3fe-b2806505ee98.png)
![image](https://user-images.githubusercontent.com/58152228/168496341-e8da0121-1f69-4a56-ac64-9db07b3666f7.png)

**Comment by brnaguiar** [comment]
```
model:
    name: "..."
    developer: $automec_dev
    date: 25-01-2022 12h40
    ml_arch: 
        name: 'rota'
        epochs: 20
        batch_size: 30
    dataset: 
          name: "..."
          cam_pose: "..."
          developer: $automec_dev
          environment: ema
          frequency: 30
          image_size: 320,160
          linear_velocity: 0
          type: parking/driving/etc
          date:  25-01-2022 12h20
          comments: "..."
    model_eval: 5*
    comments: "..."
```

```
dataset:
  name: "..."
  cam_pose: "..."
  developer: $automec_dev
  environment: ema
  frequency: 30
  image_size: 320,160
  linear_velocity: 0
  type: parking/driving/etc
  date:  25-01-2022 12h20
  comments: "..."
```
